version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: postgresql://lefterisgilmaz:admin@host.docker.internal:5432/Transactions
    extra_hosts:
      - "host.docker.internal:host-gateway"