version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: lefterisgilmaz
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Transactions
    ports:
      - "5433:5433"  
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://lefterisgilmaz:admin@host.docker.internal:5432/Transactions
    extra_hosts:
        - "host.machine:172.20.56.223"
    depends_on:
      - db

volumes:
  postgres_data:



